"""change_audit_log_entity_id_to_string

Revision ID: 0093f8604f42
Revises: 0008
Create Date: 2025-12-02 07:55:33.813558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0093f8604f42"
down_revision: Union[str, None] = "0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("audit_logs", "entity_id",
               existing_type=sa.UUID(),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("audit_logs", "entity_id",
               existing_type=sa.String(length=128),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
