"""add sequence_id

Revision ID: a1b2c3d4e5f6
Revises: f742f400ce45
Create Date: 2025-12-02 14:35:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f742f400ce45'
branch_labels = None
depends_on = None

def upgrade():
    # 1. Add sequence_id as nullable integer
    op.add_column('import_batches', sa.Column('sequence_id', sa.Integer(), nullable=True))
    
    # 2. Backfill existing rows with sequential numbers based on created_at
    # We use a CTE to calculate row numbers
    op.execute("""
        WITH numbered AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC) as rn
            FROM import_batches
        )
        UPDATE import_batches
        SET sequence_id = numbered.rn
        FROM numbered
        WHERE import_batches.id = numbered.id
    """)
    
    # 3. Add Identity to the column (Postgres 10+)
    # We need to set NOT NULL first
    op.alter_column('import_batches', 'sequence_id', nullable=False)
    
    # Add identity
    op.execute("ALTER TABLE import_batches ALTER COLUMN sequence_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1)")
    
    # 4. Sync the sequence to max(sequence_id) + 1
    # pg_get_serial_sequence returns the sequence name associated with the column
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('import_batches', 'sequence_id'),
            COALESCE((SELECT MAX(sequence_id) FROM import_batches), 0) + 1,
            false
        )
    """)

def downgrade():
    op.drop_column('import_batches', 'sequence_id')
