"""restore_amazon_stores_and_tasks

Revision ID: c233a3559730
Revises: 0011
Create Date: 2026-01-03 14:56:14.640764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c233a3559730'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually create Enum types if they don't exist
    # Create import_strategy Enum
    op.execute("DO $$ BEGIN CREATE TYPE import_strategy AS ENUM ('overwrite', 'append', 'update_only'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
        
    # Create import_status Enum
    op.execute("DO $$ BEGIN CREATE TYPE import_status AS ENUM ('pending', 'running', 'succeeded', 'failed'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
        
    # Create validation_status Enum
    op.execute("DO $$ BEGIN CREATE TYPE validation_status AS ENUM ('valid', 'warning', 'error'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    op.create_table('ai_analysis_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_cache_analysis_type'), 'ai_analysis_cache', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_ai_analysis_cache_cache_key'), 'ai_analysis_cache', ['cache_key'], unique=True)
    op.create_table('extraction_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amazon_stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('marketplace_id', sa.String(length=20), nullable=False),
    sa.Column('marketplace_name', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('sp_api_refresh_token', sa.Text(), nullable=True),
    sa.Column('advertising_api_refresh_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'marketplace_id', 'seller_id', name='uix_user_marketplace_seller')
    )
    op.create_index(op.f('ix_amazon_stores_user_id'), 'amazon_stores', ['user_id'], unique=False)
    op.create_table('extraction_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('original_data', sa.JSON(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['extraction_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_items_task_id'), 'extraction_items', ['task_id'], unique=False)
    op.create_table('keyword_optimizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('domain', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('original_title', sa.Text(), nullable=False),
    sa.Column('original_bullet_points', sa.JSON(), nullable=True),
    sa.Column('optimized_title', sa.Text(), nullable=False),
    sa.Column('optimized_bullet_points', sa.JSON(), nullable=True),
    sa.Column('backend_keywords', sa.Text(), nullable=True),
    sa.Column('optimization_report', sa.Text(), nullable=False),
    sa.Column('keywords_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_optimizations_asin'), 'keyword_optimizations', ['asin'], unique=False)
    op.create_index(op.f('ix_keyword_optimizations_user_id'), 'keyword_optimizations', ['user_id'], unique=False)
    op.create_table('product_selection_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.Integer(), nullable=False),
    sa.Column('market_score', sa.Float(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('avg_reviews', sa.Integer(), nullable=True),
    sa.Column('competition_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_selection_reports_category_id'), 'product_selection_reports', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_selection_reports_user_id'), 'product_selection_reports', ['user_id'], unique=False)
    op.create_table('ads_metric_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', 'sku', name='uix_store_ads_date_sku')
    )
    op.create_index(op.f('ix_ads_metric_snapshots_asin'), 'ads_metric_snapshots', ['asin'], unique=False)
    op.create_index(op.f('ix_ads_metric_snapshots_date'), 'ads_metric_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_ads_metric_snapshots_sku'), 'ads_metric_snapshots', ['sku'], unique=False)
    op.create_index(op.f('ix_ads_metric_snapshots_store_id'), 'ads_metric_snapshots', ['store_id'], unique=False)
    op.create_table('advertising_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('targeting_type', sa.String(length=50), nullable=False),
    sa.Column('daily_budget', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'campaign_id', name='uix_store_campaign')
    )
    op.create_index(op.f('ix_advertising_campaigns_campaign_id'), 'advertising_campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_advertising_campaigns_store_id'), 'advertising_campaigns', ['store_id'], unique=False)
    op.create_table('business_metric_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('total_sales_amount', sa.Float(), nullable=False),
    sa.Column('total_units_ordered', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('unit_session_percentage', sa.Float(), nullable=True),
    sa.Column('refunds', sa.Float(), nullable=False),
    sa.Column('refunded_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', 'sku', name='uix_store_biz_date_sku')
    )
    op.create_index(op.f('ix_business_metric_snapshots_asin'), 'business_metric_snapshots', ['asin'], unique=False)
    op.create_index(op.f('ix_business_metric_snapshots_date'), 'business_metric_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_business_metric_snapshots_sku'), 'business_metric_snapshots', ['sku'], unique=False)
    op.create_index(op.f('ix_business_metric_snapshots_store_id'), 'business_metric_snapshots', ['store_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('fba_inventory', sa.Integer(), nullable=False),
    sa.Column('inbound_inventory', sa.Integer(), nullable=False),
    sa.Column('reserved_inventory', sa.Integer(), nullable=False),
    sa.Column('unfulfillable_inventory', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', 'sku', name='uix_store_inventory_date_sku')
    )
    op.create_index(op.f('ix_inventory_snapshots_asin'), 'inventory_snapshots', ['asin'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_date'), 'inventory_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_sku'), 'inventory_snapshots', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_store_id'), 'inventory_snapshots', ['store_id'], unique=False)
    op.create_table('product_costs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('cogs', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fba_fee', sa.Float(), nullable=True),
    sa.Column('referral_fee_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', name='uix_store_sku')
    )
    op.create_index(op.f('ix_product_costs_asin'), 'product_costs', ['asin'], unique=False)
    op.create_index(op.f('ix_product_costs_sku'), 'product_costs', ['sku'], unique=False)
    op.create_index(op.f('ix_product_costs_store_id'), 'product_costs', ['store_id'], unique=False)
    op.create_table('sync_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_tasks_created_at'), 'sync_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_tasks_status'), 'sync_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_sync_tasks_store_id'), 'sync_tasks', ['store_id'], unique=False)
    op.create_index(op.f('ix_sync_tasks_sync_type'), 'sync_tasks', ['sync_type'], unique=False)
    op.create_table('advertising_ad_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('ad_group_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_bid', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['advertising_campaigns.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ad_group_id', name='uix_store_adgroup')
    )
    op.create_index(op.f('ix_advertising_ad_groups_ad_group_id'), 'advertising_ad_groups', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_advertising_ad_groups_campaign_id'), 'advertising_ad_groups', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_advertising_ad_groups_store_id'), 'advertising_ad_groups', ['store_id'], unique=False)
    op.create_table('campaign_performance_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['advertising_campaigns.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', 'campaign_id', name='uix_store_date_campaign')
    )
    op.create_index(op.f('ix_campaign_performance_snapshots_campaign_id'), 'campaign_performance_snapshots', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_performance_snapshots_date'), 'campaign_performance_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_campaign_performance_snapshots_store_id'), 'campaign_performance_snapshots', ['store_id'], unique=False)
    op.alter_column('import_batches', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'file'::character varying"))
    op.execute("ALTER TABLE import_batches ALTER COLUMN import_strategy TYPE import_strategy USING import_strategy::import_strategy")
    op.execute("ALTER TABLE import_batches ALTER COLUMN status DROP DEFAULT, ALTER COLUMN status TYPE import_status USING status::import_status, ALTER COLUMN status SET DEFAULT 'pending'::import_status")
    op.alter_column('import_batches', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_import_batches_file_hash'), 'import_batches', ['file_hash'], unique=False)
    op.execute("ALTER TABLE product_records ALTER COLUMN validation_status DROP DEFAULT, ALTER COLUMN validation_status TYPE validation_status USING validation_status::validation_status, ALTER COLUMN validation_status SET DEFAULT 'valid'::validation_status")
    op.drop_index(op.f('idx_product_batch_asin'), table_name='product_records')
    op.alter_column('system_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('system_logs', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('system_logs', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('system_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_system_logs_category'), table_name='system_logs')
    op.drop_index(op.f('idx_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('idx_system_logs_timestamp'), table_name='system_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('idx_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('idx_system_logs_category'), 'system_logs', ['category'], unique=False)
    op.alter_column('system_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('system_logs', 'resolved_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('system_logs', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('system_logs', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('idx_product_batch_asin'), 'product_records', ['batch_id', 'asin'], unique=True)
    op.alter_column('product_records', 'validation_status',
               existing_type=sa.Enum('valid', 'warning', 'error', name='validation_status'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'valid'::character varying"))
    op.drop_index(op.f('ix_import_batches_file_hash'), table_name='import_batches')
    op.alter_column('import_batches', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('import_batches', 'status',
               existing_type=sa.Enum('pending', 'running', 'succeeded', 'failed', name='import_status'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('import_batches', 'import_strategy',
               existing_type=sa.Enum('overwrite', 'append', 'update_only', name='import_strategy'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('import_batches', 'source_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'file'::character varying"))
    op.drop_index(op.f('ix_campaign_performance_snapshots_store_id'), table_name='campaign_performance_snapshots')
    op.drop_index(op.f('ix_campaign_performance_snapshots_date'), table_name='campaign_performance_snapshots')
    op.drop_index(op.f('ix_campaign_performance_snapshots_campaign_id'), table_name='campaign_performance_snapshots')
    op.drop_table('campaign_performance_snapshots')
    op.drop_index(op.f('ix_advertising_ad_groups_store_id'), table_name='advertising_ad_groups')
    op.drop_index(op.f('ix_advertising_ad_groups_campaign_id'), table_name='advertising_ad_groups')
    op.drop_index(op.f('ix_advertising_ad_groups_ad_group_id'), table_name='advertising_ad_groups')
    op.drop_table('advertising_ad_groups')
    op.drop_index(op.f('ix_sync_tasks_sync_type'), table_name='sync_tasks')
    op.drop_index(op.f('ix_sync_tasks_store_id'), table_name='sync_tasks')
    op.drop_index(op.f('ix_sync_tasks_status'), table_name='sync_tasks')
    op.drop_index(op.f('ix_sync_tasks_created_at'), table_name='sync_tasks')
    op.drop_table('sync_tasks')
    op.drop_index(op.f('ix_product_costs_store_id'), table_name='product_costs')
    op.drop_index(op.f('ix_product_costs_sku'), table_name='product_costs')
    op.drop_index(op.f('ix_product_costs_asin'), table_name='product_costs')
    op.drop_table('product_costs')
    op.drop_index(op.f('ix_inventory_snapshots_store_id'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_sku'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_date'), table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_asin'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_business_metric_snapshots_store_id'), table_name='business_metric_snapshots')
    op.drop_index(op.f('ix_business_metric_snapshots_sku'), table_name='business_metric_snapshots')
    op.drop_index(op.f('ix_business_metric_snapshots_date'), table_name='business_metric_snapshots')
    op.drop_index(op.f('ix_business_metric_snapshots_asin'), table_name='business_metric_snapshots')
    op.drop_table('business_metric_snapshots')
    op.drop_index(op.f('ix_advertising_campaigns_store_id'), table_name='advertising_campaigns')
    op.drop_index(op.f('ix_advertising_campaigns_campaign_id'), table_name='advertising_campaigns')
    op.drop_table('advertising_campaigns')
    op.drop_index(op.f('ix_ads_metric_snapshots_store_id'), table_name='ads_metric_snapshots')
    op.drop_index(op.f('ix_ads_metric_snapshots_sku'), table_name='ads_metric_snapshots')
    op.drop_index(op.f('ix_ads_metric_snapshots_date'), table_name='ads_metric_snapshots')
    op.drop_index(op.f('ix_ads_metric_snapshots_asin'), table_name='ads_metric_snapshots')
    op.drop_table('ads_metric_snapshots')
    op.drop_index(op.f('ix_product_selection_reports_user_id'), table_name='product_selection_reports')
    op.drop_index(op.f('ix_product_selection_reports_category_id'), table_name='product_selection_reports')
    op.drop_table('product_selection_reports')
    op.drop_index(op.f('ix_keyword_optimizations_user_id'), table_name='keyword_optimizations')
    op.drop_index(op.f('ix_keyword_optimizations_asin'), table_name='keyword_optimizations')
    op.drop_table('keyword_optimizations')
    op.drop_index(op.f('ix_extraction_items_task_id'), table_name='extraction_items')
    op.drop_table('extraction_items')
    op.drop_index(op.f('ix_amazon_stores_user_id'), table_name='amazon_stores')
    op.drop_table('amazon_stores')
    op.drop_table('extraction_tasks')
    op.drop_index(op.f('ix_ai_analysis_cache_cache_key'), table_name='ai_analysis_cache')
    op.drop_index(op.f('ix_ai_analysis_cache_analysis_type'), table_name='ai_analysis_cache')
    op.drop_table('ai_analysis_cache')
    # ### end Alembic commands ###
