"""add_role_to_users

Revision ID: e0ea957e596c
Revises: 2599701a02ca
Create Date: 2025-12-03 08:54:11.198639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ea957e596c'
down_revision: Union[str, None] = '2599701a02ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    
    # 2. Update existing rows
    op.execute("UPDATE users SET role = 'admin'")
    
    # 3. Alter column to be non-nullable
    op.alter_column('users', 'role', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
