"""add_campaign_and_refunds_v2

Revision ID: f1624457c280
Revises: 95e710df37fa
Create Date: 2025-12-31 03:22:08.091048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1624457c280'
down_revision: Union[str, None] = '95e710df37fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('targeting_type', sa.String(length=50), nullable=False),
    sa.Column('daily_budget', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'campaign_id', name='uix_store_campaign')
    )
    op.create_index(op.f('ix_advertising_campaigns_campaign_id'), 'advertising_campaigns', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_advertising_campaigns_store_id'), 'advertising_campaigns', ['store_id'], unique=False)
    op.create_table('advertising_ad_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('ad_group_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_bid', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['advertising_campaigns.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'ad_group_id', name='uix_store_adgroup')
    )
    op.create_index(op.f('ix_advertising_ad_groups_ad_group_id'), 'advertising_ad_groups', ['ad_group_id'], unique=False)
    op.create_index(op.f('ix_advertising_ad_groups_campaign_id'), 'advertising_ad_groups', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_advertising_ad_groups_store_id'), 'advertising_ad_groups', ['store_id'], unique=False)
    op.create_table('campaign_performance_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['advertising_campaigns.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['amazon_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', 'campaign_id', name='uix_store_date_campaign')
    )
    op.create_index(op.f('ix_campaign_performance_snapshots_campaign_id'), 'campaign_performance_snapshots', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_performance_snapshots_date'), 'campaign_performance_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_campaign_performance_snapshots_store_id'), 'campaign_performance_snapshots', ['store_id'], unique=False)
    op.add_column('business_metric_snapshots', sa.Column('refunds', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('business_metric_snapshots', sa.Column('refunded_units', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_metric_snapshots', 'refunded_units')
    op.drop_column('business_metric_snapshots', 'refunds')
    op.drop_index(op.f('ix_campaign_performance_snapshots_store_id'), table_name='campaign_performance_snapshots')
    op.drop_index(op.f('ix_campaign_performance_snapshots_date'), table_name='campaign_performance_snapshots')
    op.drop_index(op.f('ix_campaign_performance_snapshots_campaign_id'), table_name='campaign_performance_snapshots')
    op.drop_table('campaign_performance_snapshots')
    op.drop_index(op.f('ix_advertising_ad_groups_store_id'), table_name='advertising_ad_groups')
    op.drop_index(op.f('ix_advertising_ad_groups_campaign_id'), table_name='advertising_ad_groups')
    op.drop_index(op.f('ix_advertising_ad_groups_ad_group_id'), table_name='advertising_ad_groups')
    op.drop_table('advertising_ad_groups')
    op.drop_index(op.f('ix_advertising_campaigns_store_id'), table_name='advertising_campaigns')
    op.drop_index(op.f('ix_advertising_campaigns_campaign_id'), table_name='advertising_campaigns')
    op.drop_table('advertising_campaigns')
    # ### end Alembic commands ###
