"""add_ai_status_to_import_batches

Revision ID: f742f400ce45
Revises: 0008
Create Date: 2025-12-02 02:14:35.285686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f742f400ce45'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('import_batches', sa.Column('ai_status', sa.String(length=20), nullable=True))
    op.add_column('import_batches', sa.Column('ai_summary', sa.JSON(), nullable=True))
    op.add_column('import_batches', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    
    # 2. Update existing rows
    op.execute("UPDATE import_batches SET ai_status = 'none' WHERE ai_status IS NULL")
    op.execute("UPDATE import_batches SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    
    # 3. Alter to non-nullable
    op.alter_column('import_batches', 'ai_status', nullable=False)
    op.alter_column('import_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
                
    op.add_column('product_records', sa.Column('ai_features', sa.JSON(), nullable=True))
    
    # 4. Product Records ai_status
    op.add_column('product_records', sa.Column('ai_status', sa.String(length=20), nullable=True))
    op.execute("UPDATE product_records SET ai_status = 'pending' WHERE ai_status IS NULL")
    op.alter_column('product_records', 'ai_status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_records', 'ai_status')
    op.drop_column('product_records', 'ai_features')
    op.drop_column('import_batches', 'created_at')
    op.drop_column('import_batches', 'ai_summary')
    op.drop_column('import_batches', 'ai_status')
    # ### end Alembic commands ###
